name: Upload docker image to docker hub using github actions

on:
    push:
        branches: [master]
    

jobs:
    docker_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v3
            
            - name: Build docker image
              run: docker build . -t aniketnitu2026/react-app
            
            - name: Docker login
              run: echo "${{secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

            - name: Push image to dockerhub
              run: docker push aniketnitu2026/react-app:latest
            

        